import type { Metadata } from "next";
import { Sono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";

const sono = Sono({
  variable: "--font-sono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${sono.variable} antialiased h-full`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
